version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - "9000:80"
    volumes:
      - ./html:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:80"
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_DATABASE: radusers
      MYSQL_USER: null
      MYSQL_PASSWORD: null
    volumes:
      - login_mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: null

volumes:
  login_mysql:
